flask_legacy/app/routes/route.py
from datetime import datetime
import json
import os
import re
import shutil

from flask import (
    Blueprint,
    abort,
    current_app,
    flash,
    jsonify,
    redirect,
    render_template,
    request,
    send_file,
    session,
)
from sqlalchemy import desc, func, select
from werkzeug.security import check_password_hash, generate_password_hash

from config import Config
from ..classes.classes import (
    Addresses,
    Affiliates,
    Conclusions,
    Contacts,
    Documents,
    Educations,
    Poligrafs,
    Regions,
    Relations,
)
from ..depends.depend import login_required, roles_required
from ..classes.classes import Roles
from ..model.models import Person, User, models_tables
from ..model.tables import Checks, Persons, Users, db_session, tables_models
from ..handlers.handler import (
    handle_image,
    handle_json_to_dict,
    handle_get_item,
    handle_post_item,
    handle_post_resume,
    handle_xml,
    make_destination,
)

bp = Blueprint(
    "route", __name__, url_prefix="/api", static_folder=getattr(Config, "BASE_PATH")
)


@bp.post("/login/<action>")
def post_login(action):
    """
    A function that handles the login process.

    Parameters:
        action (str): The action to be performed during the login process.

    Returns:
        The function returns a tuple containing an empty string and a status code.
        The status code is either 204, 201, or 205, depending on the outcome of the login process.

    Raises:
        None
    """
    user = db_session.execute(
        select(Users).where(Users.username == request.form.get("login"))
    ).scalar_one_or_none()
    if not user or user.blocked or user.deleted:
        flash("Неверные данные", "danger")
        return render_template("/login/login.html")

    if not check_password_hash(user.passhash, request.form["password"]):
        if user.attempt < 5:
            user.attempt += 1
        else:
            user.blocked = True
        db_session.commit()
        flash("Неверные данные", "danger")
        return render_template("/login/login.html")

    if action == "update":
        pattern = r"^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,16}$"
        if re.match(pattern, request.form["new_pswd"]):
            user.passhash = generate_password_hash(request.form["new_pswd"])
            user.change_pswd = False
            user.attempt = 0
            db_session.commit()
            flash("Пароль успешно изменен", "success")
            return render_template("/login/login.html")

        flash("Новый пароль не соответствует требованиям", "danger")
        return render_template("/login/login.html")

    delta_change = datetime.now() - user.pswd_create
    if not user.change_pswd and delta_change.days < 365:
        session["user"] = user.to_dict()
        user.attempt = 0
        db_session.commit()
        return redirect("/api/index/1")
    flash("Пароль устарел и должен быть сменен", "danger")
    return render_template("/login/password.html")


@bp.get("/logout")
def get_logout():
    session.clear()
    return redirect("/login/create")


@bp.get("/users")
def get_users():
    """
    Retrieves a list of users from the database based on the provided search criteria.

    Parameters:
        item (str): The table name from which to retrieve the users.

    Returns:
        tuple: A tuple containing the JSON-encoded list of users and the HTTP status code.
    """
    search_data = request.args.get("search")
    stmt = select(Users)
    if search_data and len(search_data) > 2:
        if re.match(r"^[a-zA-z_]+", search_data):
            stmt = stmt.filter(Users.username.like("%" + search_data + "%"))
        else:
            stmt = stmt.filter(Users.fullname.like("%" + search_data + "%"))
    users = db_session.execute(stmt.order_by(desc(Users.id))).scalars()
    result = [user.to_dict() for user in users]
    return jsonify(result), 200


@bp.post("/users")
def post_user():
    """
    Handles the POST request to create a user in the database.

    This function is a route handler for the '/users' endpoint with the HTTP method POST.
    It requires a valid token for authentication.

    Parameters:
        None

    Returns:
        - If the user already exists returns an empty response with status code 205.
        - Else generates a hashed password using the default password.
        Returns an empty response with status code 201.
        - If an exception occurs during the execution of the function,
        returns an empty response with status code 400.
    """
    json_data = request.get_json()
    try:
        json_dict = User(**json_data).dict()
        user = db_session.execute(
            select(Users).filter(Users.username == json_dict.get("username"))
        ).all()
        if not user:
            json_dict["role"] = Roles.guest.value
            json_dict["region"] = Regions.main.value
            json_dict["passhash"] = generate_password_hash(
                current_app.config["DEFAULT_PASSWORD"]
            )
            db_session.add(Users(**json_dict))
            db_session.commit()
            return "", 201
        return abort(400)
    except Exception as e:
        print(e)
        return abort(400)


@bp.get("/users/<int:user_id>")
def get_user_actions(user_id):
    if session["user"]["id"] == user_id:
        return "", 205
    """
    Change a user's information in the database based on their user ID.

    Parameters:
        user_id (int): The ID of the user.

    Returns:
        The HTTP status code is 201.
    """
    user = db_session.get(Users, user_id)
    item = request.args.get("item")
    if user and item:
        if item == "drop":
            user.passhash = generate_password_hash(
                current_app.config["DEFAULT_PASSWORD"]
            )
            user.attempt = 0
            user.blocked = False
            user.change_pswd = True
        elif item == "block":
            user.blocked = not user.blocked
        elif item == "delete":
            user.deleted = not user.deleted
        elif item in [reg.value for reg in Roles]:
            user.role = item
        elif item in [reg.value for reg in Regions]:
            user.region = item
        db_session.commit()
        return "", 201
    return abort(400)


@bp.get("/index/<int:page>")
@login_required()
def get_index(page):
    """
    Retrieves a paginated list of persons from the database based on the search
    query and the user's region.

    Parameters:
        page (int): The page number of the results.

    Returns:
        tuple: A tuple containing the list of persons, a boolean indicating if
        there are more results, and a boolean indicating if the page is greater
        than 1.

    Raises:
        None
    """
    pagination = 12
    search_data = request.args.get("search")
    stmt = select(Persons, Users.fullname)
    if search_data and len(search_data) > 2:
        if search_data.isdigit():
            stmt.filter(Persons.inn.ilike("%" + search_data + "%"))
        else:
            pattern = r"^\d{2}\.\d{2}\.\d{4}$"
            query = list(map(str.upper, search_data.split()))
            if len(query):
                stmt = stmt.filter(Persons.surname.ilike(f"%{query[0]}%"))
            if len(query) > 1 and not re.match(pattern, query[1]):
                stmt = stmt.filter(Persons.firstname.ilike(f"%{query[1]}%"))
            if len(query) > 2 and not re.match(pattern, query[2]):
                stmt = stmt.filter(Persons.patronymic.ilike(f"%{query[2]}%"))
            if len(query) > 1 and re.match(pattern, query[-1]):
                stmt = stmt.filter(
                    Persons.birthday == datetime.strptime(query[-1], "%d.%m.%Y").date()
                )
    if session["user"]["region"] != Regions.main.value:
        stmt = stmt.filter(Persons.region == session["user"]["region"])
    query = db_session.execute(
        stmt.join(Users)
        .order_by(desc(Persons.id))
        .limit(pagination + 1)
        .offset((page - 1) * pagination)
    ).all()
    result = [row[0].to_dict() | {"username": row[1]} for row in query]
    has_next = len(result) > pagination
    result = result[:pagination] if has_next else result
    return render_template(
        "persons.html",
        candidates=result,
        has_next=has_next,
        has_prev=page > 1,
        page=page,
    ), 200


@bp.post("/file/<item>/<int:item_id>")
def post_file(item, item_id):
    """
    Retrieves an image file associated with a person's ID.

    Args:
        item_id (int): The ID of the person.

    Returns:
        Response: A Flask Response object containing the image file.

    Raises:
        None.
    """
    files = request.files.getlist("file")
    if not files or not files[0].filename:
        flash("Файл не выбран", "danger"), 400
        return render_template("create.html")

    if item == "persons":
        for file in files:
            json_dict = json.load(file)
            anketa = handle_json_to_dict(json_dict)
            if not anketa:
                flash("Некорректные данные", "danger")
                return render_template("create.html")
            person_id = handle_post_resume(anketa["resume"])
            if not person_id:
                flash("Некорректные данные", "danger")
                return render_template("create.html")
            for table, contents in anketa.items():
                if contents and table != "resume":
                    for content in contents:
                        if content:
                            handle_post_item(content, table, person_id)
        return redirect("/api/index/1"), 201

    person = db_session.get(Persons, item_id)
    if not person:
        return abort(400)
    try:
        if not person.destination:
            destination = make_destination(
                session["user"]["id"],
                person.surname,
                person.firstname,
                person.patronymic,
                item_id,
            )

flask_legacy/app/templates/index.html
{% extends "base.html" %}

{% block body %}
<div class="container-fluid row ps-3">
  <div class="col-2 d-print-none">
    <div class="navbar navbar-expand sticky-top fs-5 p-3">
      <div class="nav flex-column">
        <a class="nav-link text-danger fs-3 fw-bold">STAFFSEC FINTECH</a>
        <hr class="text-info" />
        <a href="{{ url_for('route.get_index', page=1) }}" class="nav-link active">
          Кандидаты
        </a>
        <hr class="text-info" />
        <a
          href="{{ url_for('route.create_resume') }}"
          class="nav-link active"
        >
          Создать
        </a>
        <hr
          class="text-info"
        />
        <a href="{{ url_for('route.get_information') }}" class="nav-link active">
          Информация
        </a>
        <hr class="text-info" />
        {% if session.user.role == 'admin' %}
        <a
          href="{{ url_for('route.get_users') }}"
          class="nav-link active"
        >
          Пользователи
        </a>
        <hr
          class="text-info"
        />
        {% endif %}
        <a href="{{ url_for('route.get_logout') }}" class="nav-link active">Выход</a>
      </div>
    </div>
  </div>
  <div class="col-9" id="staffsec" style="padding-bottom: 5vh;">
    <div class="sticky-top bg-white d-print-none p-3">
      <div class="row">
        <div class="col-10 text-center">
          {% with messages = get_flashed_messages() %}
          {% if messages %}
            <div class="py-3">
              {% for message, category in messages %}
              <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
                {{ message }}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
              </div>
              {% endfor %}
            </div>
          {% endif %}
          {% endwith %}
        </div>
        <div class="col-2 text-end text-primary">
          <i class="bi bi-person-circle fs-5">{{ session.user.username }}</i>
        </div>
      </div>
    </div>
    {% block content %}{% endblock %}
  </div>
  <div class="col-1 d-print-none"></div>
</div>
{% endblock %}
{% block footer %}
<footer class="d-flex justify-content-center border-top bg-white d-print-none" style="position: fixed; bottom: 0; width: 100%; height: 5vh;">
  <p class="text-muted mt-2">2024 STAFFSEC FINTECH</p>
</footer>
{% endblock %}

flask_legacy/app/templates/logopass.html
{% extends "base.html" %}

{% from "elements.html" import input_macro %}

{% block title %}
Вход в систему
{% endblock %}

{% block body %}
<div class="container" style="width: fit-content;">
  {% with messages = get_flashed_messages() %}
  {% if messages %}
    <div class="py-3">
      {% for message, category in messages %}
      <div class="alert alert-{{category}} alert-dismissible fade show" role="alert">
        {{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
    </div>
  {% endif %}
  {% endwith %}
  <div class="text-opacity-85 text-danger py-3">
    <h3>StaffSec - кадровая безопасность</h3>
  </div>
  <div class="border border-danger rounded p-5">
    <div class="text-opacity-85 text-primary p-3">
        {% block header %}{% endblock %}
    </div>
    <div class="row mb-3">
      {% block form %}{% endblock %}
    </div>
  </div>
</div>

<script>
function showPswd() {
  const elements = [document.getElementById("password"), document.getElementById("new_pswd"), document.getElementById("conf_pswd")];
  const eye = document.getElementById("eye");
  eye.classList.toggle("bi-eye-slash");
  elements.forEach(el => {
    if (el) {
      el.type = eye.classList.contains("bi-eye-slash") ? "text" : "password";
    }
  });
}
</script>
{% endblock %}

flask_legacy/app/templates/macros.html
{% macro label_macro(label) %}
<div class="row mb-3">
  <div class="col-2">
    {{ label }}
  </div>
  <div class="col-10 text-break">
    {{ caller() }}
  </div>
</div>
{% endmacro %}

{% macro input_macro(name, placeholder, type='text', required=false, value='') %}
<input
  class="form-control"
  id="{{ name }}"
  name="{{ name }}"
  placeholder="{{ placeholder }}"
  type="{{ type }}"
  {% if required %}required{% endif %}
  value="{{ value }}"
/>
{% endmacro %} 

{% macro textarea_macro(name, placeholder, text='') %}
<textarea
  class="form-control"
  id="{{ name }}"
  name="{{ name }}"
  placeholder="{{ placeholder }}"
  rows="3"
>{{ text }}</textarea>
{% endmacro %}

{% macro select_macro(name, options, required=false, disabled=false, value='') %}
<select
  class="form-select"
  id="{{ name }}"
  name="{{ name }}"
  {% if required %}required{% endif %}
  {% if disabled %}disabled{% endif %}
  value="{{ value }}"
>
  {% for option in options %}
  <option value="{{ option }}">{{ option }}</option>
  {% endfor %}
</select>
{% endmacro %}

{% macro switch_macro(name) %}
<div class="form-check form-switch">
  <input
    class="form-check-input"
    id="{{ name }}"
    name="{{ name }}"
    type="checkbox"
  />
</div>
{% endmacro %}

{% macro btn_group_macro(offset='offset-2') %}
<div class="{{ offset }} py-3">
  <div class="btn-group" role="group">
    <button
      class="btn btn-md btn-outline-primary"
      name="submit"
      type="submit"
    >Принять
    </button>
    <button
      class="btn btn-md btn-outline-danger"
      name="reset"
      type="reset"
    >
      Очистить
    </button>
  </div>
</div>
{% endmacro %}

flask_legacy/app/templates/persons.html
{% extends "index.html" %}

{% from "elements.html" import input_macro %}

{% block title %}
Кандидаты
{% endblock %}

{% block content %}
<div class="text-opacity-85 text-danger py-5 px-3">
  <h3>Кандидаты</h3>
</div>
<div class="row mb-3">
  <form 
    onsubmit="{{ url_for('route.get_index', page=1) }}"
    class="form form-check" 
    method="get" 
  >
    {{ input_macro("search", "Поиск по фамилии, имени, отчеству, дате рождения, инн", required=true) }}
  </form>
</div>
<div class="row py-3">
  <table class="table align-middle table-hover">
    <caption>
      <a 
        class="btn btn-link" 
        href="{{ url_for('route.get_index', page=page) }}" 
        style="text-decoration: none;"
      >
        <i class="bi bi-arrow-clockwise">Обновить</i>
      </a>
    </caption>
    <thead>
      <tr height="50px">
        <th width="5%">#</th>
        <th width="15%">Регион</th>
        <th>Фамилия Имя Отчество</th>
        <th width="15%">Дата рождения</th>
        <th width="15%">Обновлено</th>
        <th width="15%">Сотрудник</th>
        <th width="5%" class="text-center">Статус</th>
      </tr>
    </thead>
      {% for row in candidates %}
      <tr>
        <td>{{ row['id'] }}</td>
        <td>{{ row['region'] }}</td>
        <td>
          <a
            class="link-primary" 
            href="{{ url_for('route.get_profile', person_id=row['id']) }}"
            >
            {{ row['surname'] }} {{row['firstname']}} {{ row['patronymic' if row['patronymic']] }}
          </a>
        </td>
        <td>{{ row['birthday'].strftime("%d.%m.%Y") }}</td>
        <td>{{ row['created'].strftime("%d.%m.%Y") }}</td>
        <td>{{ row['username'] }}</td>
        <td class="text-center">
          {% if row.standing %}
          <div
            class="spinner-border spinner-grow-sm text-danger"
            role="status"
            :title="'Проверка'"
          >
          </div>
          {% else %}
          <div class="text-success fs-5" title="Окончено">
            <i class="bi bi-emoji-smile"></i>
          </div>
          {% endif %}
        </td>
      </tr>
      {% endfor %}
  </table>
</div>
{% if not candidates|length %}
<p class="fs-6 taxt-danger">Ничего не найдено</p>
{% endif %}

{% if has_next or has_prev %}
<nav class="mb-4">
  <ul class="pagination justify-content-center">
    {% if has_prev %}
    <li class="page-item">
      <a
        :disabled="!has_prev"
        class="link-primary" 
        href="{{ url_for('route.get_index', page=page - 1) }}"
      >
        <i class="bi bi-chevron-double-left"></i>
        Назад 
      </a>
    </li>
    {% endif %}
    {% if has_next %}
    <li class="page-item">
      <a 
        :disabled="!has_next"
        class="link-primary" 
        href="{{ url_for('route.get_index', page=page + 1) }}"
      >
        Вперёд
        <i class="bi bi-chevron-double-right"></i>
      </a>
    </li>
    {% endif %}
  </ul>
</nav>
{% endif %}
{% endblock %}